#
# SSH server for provisioning tests.
#
FROM	ubuntu

RUN	apt-get update && apt-get install -y \
		openssh-server rsync sudo

EXPOSE	22

RUN	mkdir /var/run/sshd \
	&& echo 'root:root' |chpasswd \
	&& sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config \
	&& sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config

CMD    ["/usr/sbin/sshd", "-D"]
